# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=5)),
                ('skills', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=45)),
                ('company', models.CharField(blank=True, max_length=60)),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=5)),
                ('skills', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=45)),
                ('company', models.CharField(blank=True, max_length=60)),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='mentee',
            name='teacher',
            field=models.ManyToManyField(related_name='student', to='loginreg.Mentor'),
        ),
    ]
