# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=5)),
                ('user_type', models.CharField(max_length=6)),
                ('skills', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=45)),
                ('company', models.CharField(blank=True, max_length=60)),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('relationships', models.ManyToManyField(related_name='_user_relationships_+', through='loginreg.Relationship', to='loginreg.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='loginreg.User'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='loginreg.User'),
        ),
    ]
